name: Enable Pull Request Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # Needed to merge PRs
      pull-requests: write   # Needed to enable auto-merge

    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
